version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cms_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:password@db:5432/cms_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - JWT_SECRET_KEY=jhasgkdvuk1238o6t6AGAy67LOIK
    depends_on:
      - db
      - redis
    restart: on-failure

  worker:
    build: .
    command: celery -A app.celery worker --loglevel=info
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:password@db:5432/cms_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - JWT_SECRET_KEY=jhasgkdvuk1238o6t6AGAy67LOIK
    depends_on:
      - db
      - redis
      - web
    restart: on-failure

  beat:
    build: .
    command: celery -A app.celery beat --loglevel=info
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:password@db:5432/cms_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - JWT_SECRET_KEY=jhasgkdvuk1238o6t6AGAy67LOIK
    depends_on:
      - db
      - redis
      - web
    restart: on-failure

volumes:
  postgres_data:
